'''FAST API'''

# IT is the way to connect communicate  two different services on the internet
#FAST API is a powerful tool for developers looking to create fast, efficient, and well-documented APIs.
'''DATABASE  <---->API <----- >  WEBSERVER <-----> API ----> INTERNET <-----> API ,---->  WEBAPLICATION'''
'''                                 |                                     '''                                     
'''                                 |                                      '''
# create folder via uv init FAST-API
# NOW INSTALL FAST API
# uv add fastapi[standard]
#dependencies installed
# create program to call or test get-api
# now run function
#fastapi dev main.py
# server   Server started at http://127.0.0.1:8000
# server   Documentation at http://127.0.0.1:8000/docs ------> this will work like postman
# server   Documentation at http://127.0.0.1:8000/side_hustles   
# will generates the quotes written in it JUST DISPLAY ON WEB PAGE
# server   Documentation at http://127.0.0.1:8000/money_quotes
# # will generates the quotes written in it JUST DISPLAY ON WEB PAGE

# IF WE USE THIS server   Documentation at http://127.0.0.1:8000/docs
# THIS WILL WORK LIKE POSTMAN but here swagger UI
# CLICK ON GET, TRYOUT AND EXECUTE
# WILL GENERATE QUOTES 



# now edit function putting authentication to it
# so no one ca use it without your permission
# put simple logic of if and else and api key 
#http://127.0.0.1:8000/money_quotes?apiKey=123456789      here you have to put keys
#Documentation at http://127.0.0.1:8000/docs     here it will as key


# WHAT IS SWAGGER UI
#Swagger UI is a popular open-source tool for API documentation and testing. 
# It allows developers to visualize and interact with the API’s resources without having any of the implementation logic in place. 
# This makes it easier for both backend implementation and client-side consumption

'''Swagger UI''' #is focused on creating interactive API documentation and 
#providing a user-friendly interface for testing APIs directly from the documentation.

'''Postman''' # offers a comprehensive set of tools for API development, testing, and collaboration, 
#making it suitable for managing the entire API lifecycle.
